blueprint:
  name: IKEA_MUSIC_REMOTE_v0.1
  domain: automation
  input:
    remote:
      name: Remote Control
      description: Select the remote control you wish to use.
      selector:
        device:
          integration: zha
          manufacturer: IKEA of Sweden
          model: Remote Control N2
          multiple: false
    mediaplayer:
      name: Media Player
      description: Select the Music Assistant Media Player.
      selector:
        target:
          entity:
            - domain: media_player
mode: restart
max_exceeded: silent
trigger:
- platform: event
  event_type: zha_event
  event_data:
    device_id: !input remote
action:
- choose:
  - conditions:  #Left Button - Previous Track
    - '{{ command == ''press'' }}'
    - '{{ cluster_id == 5 }}'
    - '{{ endpoint_id == 1 }}'
    - '{{ args == [257, 13, 0] }}'
    sequence:
      - service: media_player.media_previous_track
        target:
          entity_id: !input mediaplayer
  - conditions:
    - '{{ command == ''press'' }}'
    - '{{ cluster_id == 5 }}'
    - '{{ endpoint_id == 1 }}'
    - '{{ args == [256, 13, 0] }}'
    sequence:  #Right Button - Next Track
      - service: media_player.media_next_track
        target:
          entity_id: !input mediaplayer
  - conditions: #Hold Top Button - Volume Up
    - '{{ command == ''move_with_on_off'' }}'
    - '{{ cluster_id == 8 }}'
    - '{{ endpoint_id == 1 }}'
    sequence:
    - repeat:
        #count: 10
        sequence:
        - service: media_player.volume_up
          target: !input mediaplayer
  - conditions: #Hold Bottom Button - Volume Down
    - '{{ command == ''move'' }}'
    - '{{ cluster_id == 8 }}'
    - '{{ endpoint_id == 1 }}'
    sequence:
    - repeat:
        #count: 10
        sequence:
        - service: media_player.volume_down
          target: !input mediaplayer
  default: []
